### ISSUE TITLE
Error during `push`: No signatures found on invoice. At least one signature is required

### ISSUE THREAD

**Issue by ecumene** [deislabs/hippo-cli#106]
When I run `hippo push . -v development` (generated via `yo wasm`)

I get
```
Error: Error pushing bindle to server: Invalid request (status code 400): Some("signatures `No signatures found on invoice. At least one signature is required` cannot be verified")
```

I'm on OSX, I have `bindle-server --unauthenticated` and `hippo-server` running :)

**Comment by ecumene** [comment]
> [](https://github.com/deislabs/hippo-cli#external-handlers)hippo does not currently support Bindle's parcel.label.feature or signature features.

Ahh, I see.

**Comment by vdice** [comment]
@ecumene pending support for signature features in hippo, can you try running the last tagged version of bindle instead ([v0.8.0](https://github.com/deislabs/bindle/releases/tag/v0.8.0))?  I believe the signature logic came in after that and has yet to be released.
