### ISSUE TITLE
`export HIPPO_URL=https://localhost:5309/` returns error

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/hippo-cli#131]
```
$ export HIPPO_URL=https://localhost:5309/
$ hippo auth register --username admin --password 'Passw0rd!'
Error:
```

The client expected the environment variable to be the following:

```
$ export HIPPO_URL=https://localhost:5309
```

We should sanitize input, removing extra path segments from the base URL.

**Comment by adamreese** [comment]
The empty error comes from here https://github.com/deislabs/hippo-cli/blob/main/src/hippo/client.rs#L234

**Comment by bacongobbler** [comment]
irrelevant
