### ISSUE TITLE
Warn when a pattern doesn't match

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo-cli#36]
It's easy to typo a `files` pattern, or to forget to update it after your change your layout.  This results in no matches.  This is currently considered legitimate, but often it won't be.  We should provide diagnostics for this case, e.g.

* Warn if any pattern results in no match
  * Should we allow turning off this warning?
* Warn? or error? if a pattern with no wildcards results in no match (i.e. file does not exist)

What do folks think are appropriate levels in these cases?

**Comment by technosophos** [comment]
Erroring out will cause anger and frustration, of the form "I just wanted to comment/remove something for testing, and now I have to go change my `HIPPOFACTS`". So I'd be in favor of warning.

**Comment by itowlson** [comment]
That's a great point.  Warning it is.
