### ISSUE TITLE
Error message is wrong when running `hippo bindle` on a non-existent Bindle server

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo-cli#57]
From @itowlson 

> Bindle folks: I'm bit puzzled by this error.  If I push to a bad server, I appear to get an "Invoice was not found" error from the Bindle client lib, which seems misleading.  Is this expected / a known issue?  Or am I doing something wrong?

I originally filed this issue on Bindle, believing it to be a client library error:

https://github.com/deislabs/bindle/issues/207

But I am getting different results on `hippo`. So I think the bug may be a recent change to `hippo`

**Comment by technosophos** [comment]
This is what I get, testing on the fileserver repo:

```console
$ hippo bindle . -s https://fake.example.com/
Error: Error pushing bindle to server: Error creating request
```

**Comment by itowlson** [comment]
Blast, now I get that too.  Which means the problem may have been in one of my various branches.  Thanks for checking - I'll investigate further.

**Comment by itowlson** [comment]
The error changes to "Invoice was not found" if you pass `http2_prior_knowledge: false` in the `bindle::client::ClientOptions` to the `bindle::client::Client` constructor.

**Comment by bacongobbler** [comment]
Hmm... In that case bumping to the latest release of bindle (once available) should fix this, as https://github.com/deislabs/bindle/pull/203 now sets that field as `false` by default.

**Comment by itowlson** [comment]
Closing in favour of underlying issue at https://github.com/deislabs/bindle/issues/207
