### ISSUE TITLE
Hippo push does not read password from env var

### ISSUE THREAD

**Issue by simongdavies** [deislabs/hippo-cli#86]
if I set env var `BINDLE_PASSWORD` and then execute

`hippo push -k .`

I get this error

```
error: The following required arguments were not provided:
    --bindle-password <bindle_password>
```

I was expecting that hippo would read the password from my environment

**Comment by itowlson** [comment]
Can't repro this - the EV works for me.  Can you dump all Hippo/Bindle-related EVs (redacting passwords) please?

**Comment by itowlson** [comment]
Also I probably don't need to say this but can you make sure you are on 0.9.0?  There were some funnies with Clap in 0.8.0 and it was giving us all sorts of confusing and misleading errors.

**Comment by simongdavies** [comment]
Yes , definitely using 0.9.0, let me see if I can get a repro

**Comment by simongdavies** [comment]
Apologies Ivan this was my error, I didn't export the env var, it works.
