### ISSUE TITLE
Further fortifications for dev versioning strategy

### ISSUE THREAD

**Issue by vdice** [deislabs/hippo-cli#93]
When the versioning strategy for an app is dev, a few prerelease components are added to the resulting bindle version, including user name and timestamp.  We'd previously encountered instances of the timestamp bit not complying with semver (proposed fix in https://github.com/deislabs/hippo-cli/pull/92).

However, there remain areas where we could apply further rigor to ensure the bindle version is semver-compliant -- specifically around the user name.  Currently we look this value up from USER or USERNAME in the env.  Let's make sure we have logic to ensure this value can be injected as prerelease data without breaking semver compliance.  (For instance, if `USER=0foo`, this would result in a non-compliant version.)

**Comment by bacongobbler** [comment]
no longer relevant after merging https://github.com/deislabs/hippo-cli/pull/121. This is now a concern of the Spin CLI.
