### ISSUE TITLE
HTTP outbound request configuration

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo-cli#95]
The WAGI specification for bindles states that, if a handler wants to make HTTP requests, it lists the hosts it wants to access in `parcel.label.feature.wagi.allowed_hosts`.  The Hippo CLI doesn't currently provide a means to inject this.

Well, okay, we can specify a corresponding entry in `HIPPOFACTS`, whack it across into `invoice.toml`, bish bosh bash, job done.

But... the list of allowed hosts is not necessarily something we can or should nail down at compile time.  Imagine, for example, you are building a site for hosting cat videos - a fundamental requirement of the modern Web.  Your site uses Azure storage to host the actual videos, because it is modern but not _that_ modern.  And you interact with Azure storage via HTTP.

Now your site has a QA instance where the testing department can upload and verify videos of carefully curated test videos (zero cats, one cat, 99 cats, 2^32-1 cats, etc.), and a production instance where the hoi polloi can upload and share their videos.  These instances, of course, use different storage accounts.

Which have different host names.

Now at the Hippo configuration level this is easy enough to think about: we could just have stuff in the UI to say what sites each environment is allowed to access.  But the WAGI bindle spec, if I've understood it correctly, _doesn't allow for that_.  It expects the set of hosts to be defined in the bindle.  Which would mean your QA and Production instances have to be different bindles.  Which seems questionable; and if it is true means we need a different solution for HIPPOFACTS so the user doesn't need to run a prep script just to inject the right URL for the planned environment.

So... how should we go about this?  Should we remove `allowed_hosts` from the WAGI feature spec and put it somewhere else?  Or at least allow it to be overridden or extended somewhere else?  If not, how do we envisage the sort of scenario outlined above?  Or have I completely misunderstood the spec?

cc @technosophos

**Comment by radu-matei** [comment]
> The following features are available for Wagi under ...

I'm not sure why the current spec wouldn't _allow_  that.
In fact, I think there are scenarios where you want to pass a list of allowed hosts both at compile time, and at runtime (for example, a logging dependency that sends logs to an aggregation server).
Then, the user is prompted to allow or deny a certain domin.

**Comment by bacongobbler** [comment]
If WAGI does not support allowed_hosts, we could dangle a new field off the Channel model for allowed hosts, then pass that to the ReverseProxy.

https://github.com/deislabs/hippo/blob/32587897ed1ab429b01f28ba2a7401556d7983f6/src/Infrastructure/ReverseProxies/YarpReverseProxy.cs#L29-L32

**Comment by radu-matei** [comment]
I disagree with having to remove `allowed_hosts` from Wagi.
Besides, I'm not even sure _how_  you would be able to start Wagi properly without that being a Wagi config.

Apart from that, having configuration in both the parcel metadata and as channel config does make sense. We do need to figure out which takes precedence (and whether there are possibly other configuration sources).

**Comment by bacongobbler** [comment]
no longer relevant after merging https://github.com/deislabs/hippo-cli/pull/121.
