### ISSUE TITLE
`spin deploy`: Create App, Channel, and Revision from a bindle ID

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/hippo-cli#97]
I as a user have a Bindle storage ID and a revision number. I want Hippo to take that information and

- create an App using this storage ID
- create a Channel with an automatically generated URL
- pointing at that revision number

The experience should look similar to this:

```
><> hippo serve bacongobbler/toast-on-demand 0.3.0
https://759b3fac-7290-4405-bd07-2d217a3d8c17.hippofactory.dev
```

**Comment by michelleN** [comment]
This would be amazing @bacongobbler !

**Comment by bacongobbler** [comment]
Now available as `spin deploy`. https://github.com/fermyon/spin/blob/main/src/commands/deploy.rs
